#!/bin/bash

sm --start AUTH AUTH_LOGIN_API AUTH_LOGIN_STUB USER_DETAILS IDENTITY_VERIFICATION CA_FRONTEND BAS_GATEWAY_FRONTEND THIRD_PARTY_DELEGATED_AUTHORITY THIRD_PARTY_APPLICATION BAS_GATEWAY DATASTREAM BAS_PROXY BAS_STUBS BAS_STUB_FRONTEND

./run_local.sh